POST http://localhost:3002/api/scoobygang/
Content-Type: application/json

{
  "name":"Scrappy Doo",
  "imgURL":"",
  "description":"The puppy"
}

###

POST http://localhost:3002/api/scoobygang/
Content-Type: application/json
